# Generated by Django 6.0 on 2025-12-14 23:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('is_blocked', models.BooleanField(default=False)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('last_login_attempt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
